# Generated by Django 3.2.15 on 2023-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('decription', models.TextField()),
                ('hasDiscussion', models.BooleanField()),
            ],
        ),
    ]
