<<<<<<< Updated upstream
# Generated by Django 3.2.18 on 2023-05-13 15:24
=======
# Generated by Django 4.1.7 on 2023-05-13 03:39
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
<<<<<<< Updated upstream
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courseNumber', models.IntegerField(default=0)),
                ('courseName', models.CharField(blank=True, default='Name', max_length=100)),
                ('courseSection', models.IntegerField(default=0)),
                ('courseDescription', models.TextField(blank=True, default='Description', null=True)),
                ('instructor', models.CharField(default='Instructor', max_length=100)),
                ('days', models.CharField(default='', max_length=100)),
                ('startTime', models.TimeField(default='00:00:00')),
                ('endTime', models.TimeField(default='00:00:00')),
                ('hasDiscussion', models.BooleanField(default=False)),
                ('homeworkGradedInMeetings', models.BooleanField(default=False)),
                ('officeHoursPerWeek', models.IntegerField(default=0)),
                ('relevantInfo', models.TextField(blank=True, null=True)),
                ('numberOfTAs', models.IntegerField(default=0)),
                ('numberOfAcceptedTAs', models.IntegerField(default=0)),
                ('systemStatus', models.BooleanField(default=True)),
                ('instructorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("courseNumber", models.IntegerField(default=0)),
                (
                    "courseName",
                    models.CharField(blank=True, default="Name", max_length=100),
                ),
                ("courseSection", models.IntegerField(default=0)),
                (
                    "courseDescription",
                    models.TextField(blank=True, default="Description", null=True),
                ),
                ("instructor", models.CharField(default="Instructor", max_length=100)),
                ("days", models.CharField(default="", max_length=100)),
                ("startTime", models.TimeField(default="00:00:00")),
                ("endTime", models.TimeField(default="00:00:00")),
                ("hasDiscussion", models.BooleanField(default=False)),
                ("homeworkGradedInMeetings", models.BooleanField(default=False)),
                ("officeHoursPerWeek", models.IntegerField(default=0)),
                ("relevantInfo", models.TextField(blank=True, null=True)),
                ("numberOfTAs", models.IntegerField(default=0)),
                ("numberOfAcceptedTAs", models.IntegerField(default=0)),
                (
                    "instructorUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> Stashed changes
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
<<<<<<< Updated upstream
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedApplications', models.PositiveIntegerField(default=0)),
                ('hired', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usedApplications", models.PositiveIntegerField(default=0)),
                ("hired", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> Stashed changes
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discussionNumber", models.IntegerField(default=0)),
                ("days", models.CharField(default="", max_length=100)),
                ("startTime", models.TimeField(default="00:00:00")),
                ("endTime", models.TimeField(default="00:00:00")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
    ]
