# Generated by Django 3.2.15 on 2023-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
