# Generated by Django 3.2.15 on 2023-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
