# Generated by Django 3.2.15 on 2023-03-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussionNumber', models.IntegerField(default=0)),
                ('days', models.CharField(default='', max_length=100)),
                ('startTime', models.TimeField(default='00:00:00')),
                ('endTime', models.TimeField(default='00:00:00')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
