# Generated by Django 3.2.15 on 2023-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numberOfTAs',
            field=models.IntegerField(default=0),
        ),
    ]
