# Generated by Django 3.2.15 on 2023-03-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=100)),
                ('email', models.CharField(blank=True, default='Email', max_length=100)),
                ('eagleID', models.IntegerField(default=0)),
                ('courseHistory', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
