<<<<<<< Updated upstream
# Generated by Django 3.2.18 on 2023-05-13 15:24
=======
# Generated by Django 4.1.7 on 2023-05-13 03:39
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
<<<<<<< Updated upstream
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='Name', max_length=100)),
                ('email', models.CharField(blank=True, default='Email', max_length=100)),
                ('eagleID', models.IntegerField(default=0)),
                ('courseHistory', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('pendingInstructorAccept', models.BooleanField(default=True)),
                ('acceptedByStudent', models.BooleanField(default=False)),
                ('cohort', models.CharField(blank=True, choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20, null=True)),
                ('relation', models.CharField(blank=True, choices=[('Major BS', 'Major BS'), ('Major BA', 'Major BA'), ('Minor', 'Minor'), ('Other', 'Other')], max_length=20, null=True)),
                ('applicantUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="Name", max_length=100)),
                (
                    "email",
                    models.CharField(blank=True, default="Email", max_length=100),
                ),
                ("eagleID", models.IntegerField(default=0)),
                ("courseHistory", models.TextField(blank=True, null=True)),
                ("interest", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("pendingInstructorAccept", models.BooleanField(default=True)),
                ("acceptedByStudent", models.BooleanField(default=False)),
                ("rejectedByStudent", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Freshman", "Freshman"),
                            ("Sophomore", "Sophomore"),
                            ("Junior", "Junior"),
                            ("Senior", "Senior"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Major BS", "Major BS"),
                            ("Major BA", "Major BA"),
                            ("Minor", "Minor"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "applicantUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                    ),
                ),
>>>>>>> Stashed changes
            ],
        ),
    ]
